apiVersion: backstage.io/v1alpha1
kind: component
metadata:
  name: angular-pwa-poc-api
  description: Terrible api that drives the PWA POC
  tags:
    - dotnet
spec:
  type: openapi
  lifecycle: production
  owner: Pete
  
  
